export const hiraganaWords = [
  ["あかるい", "akarui", "Bright"],
  ["いぬ", "inu", "Dog"],
  ["うたう", "utau", "Sing"],
  ["えいが", "eiga", "Movie"],
  ["おとこのこ", "otokonoko", "Boy"],
  ["かばん", "kaban", "Bag"],
  ["きのう", "kinou", "Yesterday"],
  ["くるま", "kuruma", "Car"],
  ["けんこう", "kenkou", "Health"],
  ["こたえる", "kotaeru", "Answer"],
  ["さくらんぼ", "sakuranbo", "Cherry"],
  ["しんぶん", "shinbun", "Newspaper"],
  ["すきな", "sukina", "Favorite"],
  ["せんせい", "sensei", "Teacher"],
  ["そと", "soto", "Outside"],
  ["たかい", "takai", "High"],
  ["ちいさい", "chiisai", "Small"],
  ["つくえ", "tsukue", "Desk"],
  ["てがみ", "tegami", "Letter"],
  ["とけい", "tokei", "Clock"],
  ["なつ", "natsu", "Summer"],
  ["にほん", "nihon", "Japan"],
  ["ぬいぐるみ", "nuigurumi", "Stuffed animal"],
  ["ねこ", "neko", "Cat"],
  ["のみもの", "nomimono", "Drink"],
  ["はな", "hana", "Flower"],
  ["ひるごはん", "hirugohan", "Lunch"],
  ["ふるい", "furui", "Old"],
  ["へや", "heya", "Room"],
  ["ほしい", "hoshii", "Want"],
  ["まど", "mado", "Window"],
  ["みかん", "mikan", "Mandarin orange"],
  ["むずかしい", "muzukashii", "Difficult"],
  ["めがね", "megane", "Glasses"],
  ["もちろん", "mochiron", "Of course"],
  ["やさい", "yasai", "Vegetables"],
  ["ゆめ", "yume", "Dream"],
  ["よる", "yoru", "Night"],
  ["らくだ", "rakuda", "Camel"],
  ["りんご", "ringo", "Apple"],
  ["るす", "rusu", "Absence"],
  ["れんしゅう", "renshuu", "Practice"],
  ["ろうか", "rouka", "Corridor"],
  ["わらう", "warau", "Laugh"],
  ["あじ", "aji", "Flavor"],
  ["いちご", "ichigo", "Strawberry"],
  ["うみ", "umi", "Sea"],
  ["えき", "eki", "Station"],
  ["おおきい", "ookii", "Big"],
  ["かお", "kao", "Face"],
  ["きれい", "kirei", "Beautiful"],
  ["くつ", "kutsu", "Shoes"],
  ["けさ", "kesa", "This morning"],
  ["こども", "kodomo", "Child"],
  ["さく", "saku", "Bloom"],
  ["しんせん", "shinsen", "Fresh"],
  ["すこし", "sukoshi", "A little"],
  ["たべもの", "tabemono", "Food"],
  ["とり", "tori", "Bird"],
  ["ながい", "nagai", "Long"],
  ["にちようび", "nichiyoubi", "Sunday"],
  ["ぬくい", "nukui", "Warm"],
  ["ねる", "neru", "Sleep"],
  ["のる", "noru", "Ride"],
  ["はし", "hashi", "Chopsticks"],
  ["ひと", "hito", "Person"],
  ["ふたつ", "futatsu", "Two"],
  ["へん", "hen", "Strange"],
  ["ほし", "hoshi", "Star"],
  ["まるい", "marui", "Round"],
  ["みず", "mizu", "Water"],
  ["むらさき", "murasaki", "Purple"],
  ["め", "me", "Eye"],
  ["もち", "mochi", "Rice cake"],
  ["やおや", "yaoya", "Greengrocer"],
  ["ゆき", "yuki", "Snow"],
  ["よむ", "yomu", "Read"],
  ["らいしゅう", "raishuu", "Next week"],
  ["りゅうがくせい", "ryuugakusei", "Foreign student"],
  ["るすばん", "rusuban", "House-sitting"],
  ["れきし", "rekishi", "History"],
  ["ろうじん", "roujin", "Elderly person"],
  ["わたし", "watashi", "I, me"],
  ["あおい", "aoi", "Blue"],
  ["いただきます", "itadakimasu", "I humbly receive (said before meals)"],
  ["うつくしい", "utsukushii", "Beautiful"],
  ["えんぴつ", "enpitsu", "Pencil"],
  ["おかし", "okashi", "Sweets"],
  ["かおり", "kaori", "Fragrance"],
  ["きみ", "kimi", "You"],
  ["くる", "kuru", "Come"],
  ["けいさつ", "keisatsu", "Police"],
  ["こづつみ", "kodzutsumi", "Small package"],
  ["さくぶん", "sakubun", "Composition"],
  ["しょうがっこう", "shougakkou", "Elementary school"],
  ["すうがく", "suugaku", "Mathematics"],
  ["たつ", "tatsu", "Stand up"],
  ["ちかてつ", "chikatetsu", "Subway"],
  ["つくる", "tsukuru", "Make"],
  ["なる", "naru", "Become"]
]

export const katakanaWords = [
  ["アイスクリーム", "aisukuri-mu", "Ice Cream"],
  ["ウィンドウ", "uindou", "Window"],
  ["エレベーター", "erebe-ta-", "Elevator"],
  ["オレンジ", "orenji", "Orange"],
  ["カメレオン", "kamereon", "Chameleon"],
  ["キャンセル", "kyanseru", "Cancel"],
  ["クリスマス", "kurisumasu", "Christmas"],
  ["ケーキ", "ke-ki", "Cake"],
  ["コンピューター", "konpyu-ta-", "Computer"],
  ["サラダ", "sarada", "Salad"],
  ["シャワー", "shawa-", "Shower"],
  ["スマートフォン", "suma-tofon", "Smartphone"],
  ["センター", "senta-", "Center"],
  ["ソファー", "sofa-", "Sofa"],
  ["タクシー", "takushi-", "Taxi"],
  ["テレビ", "terebi", "Television"],
  ["トマト", "tomato", "Tomato"],
  ["ナンバー", "nanba-", "Number"],
  ["ネクタイ", "nekutai", "Necktie"],
  ["ハンバーガー", "hanba-ga-", "Hamburger"],
  ["バス", "basu", "Bus"],
  ["ビール", "bi-ru", "Beer"],
  ["フィルム", "firumu", "Film"],
  ["プレゼント", "purezento", "Present"],
  ["ベッド", "beddo", "Bed"],
  ["ペン", "pen", "Pen"],
  ["ホテル", "hoteru", "Hotel"],
  ["マンション", "manshon", "Apartment"],
  ["ミルク", "miruku", "Milk"],
  ["メニュー", "menyu-", "Menu"],
  ["ユーモア", "yu-moa", "Humor"],
  ["ラーメン", "ra-men", "Ramen"],
  ["リンゴ", "ringo", "Apple"],
  ["ルール", "ru-ru", "Rule"],
  ["レストラン", "resutoran", "Restaurant"],
  ["ワイン", "wain", "Wine"]
]

